#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Practice.Resource", IsApplication=true)]

namespace Practice
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Font
		{
			
			// aapt resource value: 0x7F020000
			public const int sourcesanspro = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int SourceSansPro_bold = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int SourceSansPro_italic = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int SourceSansPro_regular = 2130837507;
			
			static Font()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Font()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int autocomplete_country = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int btnTransferFont = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int editFirstName = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int get_timestamp_button = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int MAutoText = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int message_textview = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int readAsset = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int restart_timestamp_service_button = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int saveButton = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int someText = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int stop_timestamp_service_button = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int testBundle = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int testMultiAutoCompleteTextView = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int testService = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int textView1 = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int textViewFont = 2130903055;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int HelloAutoComplete = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MultiAutoCompleteTextView = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int Timestamp = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_description = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int button_bundle_info = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int enter_info = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int get_timestamp_button_text = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int mutiAuto_button = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int restart_timestamp_service_button_text = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int save_info = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int service_not_connected = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int service_started = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int stop_timestamp_service_button_text = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int time_service_button = 2131099660;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
