#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FromPractice.Droid.Resource", IsApplication=true)]

namespace FromPractice.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F070006
			public const int abc_ab_share_pack_mtrl_alpha = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int abc_action_bar_item_background_material = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int abc_btn_borderless_material = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int abc_btn_check_material = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int abc_btn_check_to_on_mtrl_000 = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int abc_btn_check_to_on_mtrl_015 = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int abc_btn_colored_material = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int abc_btn_default_mtrl_shape = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int abc_btn_radio_material = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int abc_btn_radio_to_on_mtrl_000 = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int abc_btn_radio_to_on_mtrl_015 = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int abc_btn_switch_to_on_mtrl_00001 = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int abc_btn_switch_to_on_mtrl_00012 = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int abc_cab_background_internal_bg = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int abc_cab_background_top_material = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int abc_cab_background_top_mtrl_alpha = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int abc_control_background_material = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int abc_dialog_material_background = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int abc_edit_text_material = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int abc_ic_ab_back_material = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int abc_ic_arrow_drop_right_black_24dp = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int abc_ic_clear_material = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int abc_ic_commit_search_api_mtrl_alpha = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int abc_ic_go_search_api_material = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int abc_ic_menu_copy_mtrl_am_alpha = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int abc_ic_menu_cut_mtrl_alpha = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int abc_ic_menu_overflow_material = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int abc_ic_menu_paste_mtrl_am_alpha = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int abc_ic_menu_selectall_mtrl_alpha = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int abc_ic_menu_share_mtrl_alpha = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int abc_ic_search_api_material = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int abc_ic_star_black_16dp = 2131165221;
			
			// aapt resource value: 0x7F070026
			public const int abc_ic_star_black_36dp = 2131165222;
			
			// aapt resource value: 0x7F070027
			public const int abc_ic_star_black_48dp = 2131165223;
			
			// aapt resource value: 0x7F070028
			public const int abc_ic_star_half_black_16dp = 2131165224;
			
			// aapt resource value: 0x7F070029
			public const int abc_ic_star_half_black_36dp = 2131165225;
			
			// aapt resource value: 0x7F07002A
			public const int abc_ic_star_half_black_48dp = 2131165226;
			
			// aapt resource value: 0x7F07002B
			public const int abc_ic_voice_search_api_material = 2131165227;
			
			// aapt resource value: 0x7F07002C
			public const int abc_item_background_holo_dark = 2131165228;
			
			// aapt resource value: 0x7F07002D
			public const int abc_item_background_holo_light = 2131165229;
			
			// aapt resource value: 0x7F07002E
			public const int abc_list_divider_material = 2131165230;
			
			// aapt resource value: 0x7F07002F
			public const int abc_list_divider_mtrl_alpha = 2131165231;
			
			// aapt resource value: 0x7F070030
			public const int abc_list_focused_holo = 2131165232;
			
			// aapt resource value: 0x7F070031
			public const int abc_list_longpressed_holo = 2131165233;
			
			// aapt resource value: 0x7F070032
			public const int abc_list_pressed_holo_dark = 2131165234;
			
			// aapt resource value: 0x7F070033
			public const int abc_list_pressed_holo_light = 2131165235;
			
			// aapt resource value: 0x7F070034
			public const int abc_list_selector_background_transition_holo_dark = 2131165236;
			
			// aapt resource value: 0x7F070035
			public const int abc_list_selector_background_transition_holo_light = 2131165237;
			
			// aapt resource value: 0x7F070036
			public const int abc_list_selector_disabled_holo_dark = 2131165238;
			
			// aapt resource value: 0x7F070037
			public const int abc_list_selector_disabled_holo_light = 2131165239;
			
			// aapt resource value: 0x7F070038
			public const int abc_list_selector_holo_dark = 2131165240;
			
			// aapt resource value: 0x7F070039
			public const int abc_list_selector_holo_light = 2131165241;
			
			// aapt resource value: 0x7F07003A
			public const int abc_menu_hardkey_panel_mtrl_mult = 2131165242;
			
			// aapt resource value: 0x7F07003B
			public const int abc_popup_background_mtrl_mult = 2131165243;
			
			// aapt resource value: 0x7F07003C
			public const int abc_ratingbar_indicator_material = 2131165244;
			
			// aapt resource value: 0x7F07003D
			public const int abc_ratingbar_material = 2131165245;
			
			// aapt resource value: 0x7F07003E
			public const int abc_ratingbar_small_material = 2131165246;
			
			// aapt resource value: 0x7F07003F
			public const int abc_scrubber_control_off_mtrl_alpha = 2131165247;
			
			// aapt resource value: 0x7F070040
			public const int abc_scrubber_control_to_pressed_mtrl_000 = 2131165248;
			
			// aapt resource value: 0x7F070041
			public const int abc_scrubber_control_to_pressed_mtrl_005 = 2131165249;
			
			// aapt resource value: 0x7F070042
			public const int abc_scrubber_primary_mtrl_alpha = 2131165250;
			
			// aapt resource value: 0x7F070043
			public const int abc_scrubber_track_mtrl_alpha = 2131165251;
			
			// aapt resource value: 0x7F070044
			public const int abc_seekbar_thumb_material = 2131165252;
			
			// aapt resource value: 0x7F070045
			public const int abc_seekbar_tick_mark_material = 2131165253;
			
			// aapt resource value: 0x7F070046
			public const int abc_seekbar_track_material = 2131165254;
			
			// aapt resource value: 0x7F070047
			public const int abc_spinner_mtrl_am_alpha = 2131165255;
			
			// aapt resource value: 0x7F070048
			public const int abc_spinner_textfield_background_material = 2131165256;
			
			// aapt resource value: 0x7F070049
			public const int abc_switch_thumb_material = 2131165257;
			
			// aapt resource value: 0x7F07004A
			public const int abc_switch_track_mtrl_alpha = 2131165258;
			
			// aapt resource value: 0x7F07004B
			public const int abc_tab_indicator_material = 2131165259;
			
			// aapt resource value: 0x7F07004C
			public const int abc_tab_indicator_mtrl_alpha = 2131165260;
			
			// aapt resource value: 0x7F070054
			public const int abc_textfield_activated_mtrl_alpha = 2131165268;
			
			// aapt resource value: 0x7F070055
			public const int abc_textfield_default_mtrl_alpha = 2131165269;
			
			// aapt resource value: 0x7F070056
			public const int abc_textfield_search_activated_mtrl_alpha = 2131165270;
			
			// aapt resource value: 0x7F070057
			public const int abc_textfield_search_default_mtrl_alpha = 2131165271;
			
			// aapt resource value: 0x7F070058
			public const int abc_textfield_search_material = 2131165272;
			
			// aapt resource value: 0x7F07004D
			public const int abc_text_cursor_material = 2131165261;
			
			// aapt resource value: 0x7F07004E
			public const int abc_text_select_handle_left_mtrl_dark = 2131165262;
			
			// aapt resource value: 0x7F07004F
			public const int abc_text_select_handle_left_mtrl_light = 2131165263;
			
			// aapt resource value: 0x7F070050
			public const int abc_text_select_handle_middle_mtrl_dark = 2131165264;
			
			// aapt resource value: 0x7F070051
			public const int abc_text_select_handle_middle_mtrl_light = 2131165265;
			
			// aapt resource value: 0x7F070052
			public const int abc_text_select_handle_right_mtrl_dark = 2131165266;
			
			// aapt resource value: 0x7F070053
			public const int abc_text_select_handle_right_mtrl_light = 2131165267;
			
			// aapt resource value: 0x7F070059
			public const int abc_vector_test = 2131165273;
			
			// aapt resource value: 0x7F07005A
			public const int adduser = 2131165274;
			
			// aapt resource value: 0x7F07005B
			public const int avd_hide_password = 2131165275;
			
			// aapt resource value: 0x7F07005C
			public const int avd_show_password = 2131165276;
			
			// aapt resource value: 0x7F07005D
			public const int csharp = 2131165277;
			
			// aapt resource value: 0x7F07005E
			public const int design_bottom_navigation_item_background = 2131165278;
			
			// aapt resource value: 0x7F07005F
			public const int design_fab_background = 2131165279;
			
			// aapt resource value: 0x7F070060
			public const int design_ic_visibility = 2131165280;
			
			// aapt resource value: 0x7F070061
			public const int design_ic_visibility_off = 2131165281;
			
			// aapt resource value: 0x7F070062
			public const int design_password_eye = 2131165282;
			
			// aapt resource value: 0x7F070063
			public const int design_snackbar_background = 2131165283;
			
			// aapt resource value: 0x7F070118
			public const int Icon = 2131165464;
			
			// aapt resource value: 0x7F070064
			public const int ic_audiotrack_dark = 2131165284;
			
			// aapt resource value: 0x7F070065
			public const int ic_audiotrack_light = 2131165285;
			
			// aapt resource value: 0x7F070066
			public const int ic_dialog_close_dark = 2131165286;
			
			// aapt resource value: 0x7F070067
			public const int ic_dialog_close_light = 2131165287;
			
			// aapt resource value: 0x7F070068
			public const int ic_group_collapse_00 = 2131165288;
			
			// aapt resource value: 0x7F070069
			public const int ic_group_collapse_01 = 2131165289;
			
			// aapt resource value: 0x7F07006A
			public const int ic_group_collapse_02 = 2131165290;
			
			// aapt resource value: 0x7F07006B
			public const int ic_group_collapse_03 = 2131165291;
			
			// aapt resource value: 0x7F07006C
			public const int ic_group_collapse_04 = 2131165292;
			
			// aapt resource value: 0x7F07006D
			public const int ic_group_collapse_05 = 2131165293;
			
			// aapt resource value: 0x7F07006E
			public const int ic_group_collapse_06 = 2131165294;
			
			// aapt resource value: 0x7F07006F
			public const int ic_group_collapse_07 = 2131165295;
			
			// aapt resource value: 0x7F070070
			public const int ic_group_collapse_08 = 2131165296;
			
			// aapt resource value: 0x7F070071
			public const int ic_group_collapse_09 = 2131165297;
			
			// aapt resource value: 0x7F070072
			public const int ic_group_collapse_10 = 2131165298;
			
			// aapt resource value: 0x7F070073
			public const int ic_group_collapse_11 = 2131165299;
			
			// aapt resource value: 0x7F070074
			public const int ic_group_collapse_12 = 2131165300;
			
			// aapt resource value: 0x7F070075
			public const int ic_group_collapse_13 = 2131165301;
			
			// aapt resource value: 0x7F070076
			public const int ic_group_collapse_14 = 2131165302;
			
			// aapt resource value: 0x7F070077
			public const int ic_group_collapse_15 = 2131165303;
			
			// aapt resource value: 0x7F070078
			public const int ic_group_expand_00 = 2131165304;
			
			// aapt resource value: 0x7F070079
			public const int ic_group_expand_01 = 2131165305;
			
			// aapt resource value: 0x7F07007A
			public const int ic_group_expand_02 = 2131165306;
			
			// aapt resource value: 0x7F07007B
			public const int ic_group_expand_03 = 2131165307;
			
			// aapt resource value: 0x7F07007C
			public const int ic_group_expand_04 = 2131165308;
			
			// aapt resource value: 0x7F07007D
			public const int ic_group_expand_05 = 2131165309;
			
			// aapt resource value: 0x7F07007E
			public const int ic_group_expand_06 = 2131165310;
			
			// aapt resource value: 0x7F07007F
			public const int ic_group_expand_07 = 2131165311;
			
			// aapt resource value: 0x7F070080
			public const int ic_group_expand_08 = 2131165312;
			
			// aapt resource value: 0x7F070081
			public const int ic_group_expand_09 = 2131165313;
			
			// aapt resource value: 0x7F070082
			public const int ic_group_expand_10 = 2131165314;
			
			// aapt resource value: 0x7F070083
			public const int ic_group_expand_11 = 2131165315;
			
			// aapt resource value: 0x7F070084
			public const int ic_group_expand_12 = 2131165316;
			
			// aapt resource value: 0x7F070085
			public const int ic_group_expand_13 = 2131165317;
			
			// aapt resource value: 0x7F070086
			public const int ic_group_expand_14 = 2131165318;
			
			// aapt resource value: 0x7F070087
			public const int ic_group_expand_15 = 2131165319;
			
			// aapt resource value: 0x7F070088
			public const int ic_media_pause_dark = 2131165320;
			
			// aapt resource value: 0x7F070089
			public const int ic_media_pause_light = 2131165321;
			
			// aapt resource value: 0x7F07008A
			public const int ic_media_play_dark = 2131165322;
			
			// aapt resource value: 0x7F07008B
			public const int ic_media_play_light = 2131165323;
			
			// aapt resource value: 0x7F07008C
			public const int ic_media_stop_dark = 2131165324;
			
			// aapt resource value: 0x7F07008D
			public const int ic_media_stop_light = 2131165325;
			
			// aapt resource value: 0x7F07008E
			public const int ic_mr_button_connected_00_dark = 2131165326;
			
			// aapt resource value: 0x7F07008F
			public const int ic_mr_button_connected_00_light = 2131165327;
			
			// aapt resource value: 0x7F070090
			public const int ic_mr_button_connected_01_dark = 2131165328;
			
			// aapt resource value: 0x7F070091
			public const int ic_mr_button_connected_01_light = 2131165329;
			
			// aapt resource value: 0x7F070092
			public const int ic_mr_button_connected_02_dark = 2131165330;
			
			// aapt resource value: 0x7F070093
			public const int ic_mr_button_connected_02_light = 2131165331;
			
			// aapt resource value: 0x7F070094
			public const int ic_mr_button_connected_03_dark = 2131165332;
			
			// aapt resource value: 0x7F070095
			public const int ic_mr_button_connected_03_light = 2131165333;
			
			// aapt resource value: 0x7F070096
			public const int ic_mr_button_connected_04_dark = 2131165334;
			
			// aapt resource value: 0x7F070097
			public const int ic_mr_button_connected_04_light = 2131165335;
			
			// aapt resource value: 0x7F070098
			public const int ic_mr_button_connected_05_dark = 2131165336;
			
			// aapt resource value: 0x7F070099
			public const int ic_mr_button_connected_05_light = 2131165337;
			
			// aapt resource value: 0x7F07009A
			public const int ic_mr_button_connected_06_dark = 2131165338;
			
			// aapt resource value: 0x7F07009B
			public const int ic_mr_button_connected_06_light = 2131165339;
			
			// aapt resource value: 0x7F07009C
			public const int ic_mr_button_connected_07_dark = 2131165340;
			
			// aapt resource value: 0x7F07009D
			public const int ic_mr_button_connected_07_light = 2131165341;
			
			// aapt resource value: 0x7F07009E
			public const int ic_mr_button_connected_08_dark = 2131165342;
			
			// aapt resource value: 0x7F07009F
			public const int ic_mr_button_connected_08_light = 2131165343;
			
			// aapt resource value: 0x7F0700A0
			public const int ic_mr_button_connected_09_dark = 2131165344;
			
			// aapt resource value: 0x7F0700A1
			public const int ic_mr_button_connected_09_light = 2131165345;
			
			// aapt resource value: 0x7F0700A2
			public const int ic_mr_button_connected_10_dark = 2131165346;
			
			// aapt resource value: 0x7F0700A3
			public const int ic_mr_button_connected_10_light = 2131165347;
			
			// aapt resource value: 0x7F0700A4
			public const int ic_mr_button_connected_11_dark = 2131165348;
			
			// aapt resource value: 0x7F0700A5
			public const int ic_mr_button_connected_11_light = 2131165349;
			
			// aapt resource value: 0x7F0700A6
			public const int ic_mr_button_connected_12_dark = 2131165350;
			
			// aapt resource value: 0x7F0700A7
			public const int ic_mr_button_connected_12_light = 2131165351;
			
			// aapt resource value: 0x7F0700A8
			public const int ic_mr_button_connected_13_dark = 2131165352;
			
			// aapt resource value: 0x7F0700A9
			public const int ic_mr_button_connected_13_light = 2131165353;
			
			// aapt resource value: 0x7F0700AA
			public const int ic_mr_button_connected_14_dark = 2131165354;
			
			// aapt resource value: 0x7F0700AB
			public const int ic_mr_button_connected_14_light = 2131165355;
			
			// aapt resource value: 0x7F0700AC
			public const int ic_mr_button_connected_15_dark = 2131165356;
			
			// aapt resource value: 0x7F0700AD
			public const int ic_mr_button_connected_15_light = 2131165357;
			
			// aapt resource value: 0x7F0700AE
			public const int ic_mr_button_connected_16_dark = 2131165358;
			
			// aapt resource value: 0x7F0700AF
			public const int ic_mr_button_connected_16_light = 2131165359;
			
			// aapt resource value: 0x7F0700B0
			public const int ic_mr_button_connected_17_dark = 2131165360;
			
			// aapt resource value: 0x7F0700B1
			public const int ic_mr_button_connected_17_light = 2131165361;
			
			// aapt resource value: 0x7F0700B2
			public const int ic_mr_button_connected_18_dark = 2131165362;
			
			// aapt resource value: 0x7F0700B3
			public const int ic_mr_button_connected_18_light = 2131165363;
			
			// aapt resource value: 0x7F0700B4
			public const int ic_mr_button_connected_19_dark = 2131165364;
			
			// aapt resource value: 0x7F0700B5
			public const int ic_mr_button_connected_19_light = 2131165365;
			
			// aapt resource value: 0x7F0700B6
			public const int ic_mr_button_connected_20_dark = 2131165366;
			
			// aapt resource value: 0x7F0700B7
			public const int ic_mr_button_connected_20_light = 2131165367;
			
			// aapt resource value: 0x7F0700B8
			public const int ic_mr_button_connected_21_dark = 2131165368;
			
			// aapt resource value: 0x7F0700B9
			public const int ic_mr_button_connected_21_light = 2131165369;
			
			// aapt resource value: 0x7F0700BA
			public const int ic_mr_button_connected_22_dark = 2131165370;
			
			// aapt resource value: 0x7F0700BB
			public const int ic_mr_button_connected_22_light = 2131165371;
			
			// aapt resource value: 0x7F0700BC
			public const int ic_mr_button_connected_23_dark = 2131165372;
			
			// aapt resource value: 0x7F0700BD
			public const int ic_mr_button_connected_23_light = 2131165373;
			
			// aapt resource value: 0x7F0700BE
			public const int ic_mr_button_connected_24_dark = 2131165374;
			
			// aapt resource value: 0x7F0700BF
			public const int ic_mr_button_connected_24_light = 2131165375;
			
			// aapt resource value: 0x7F0700C0
			public const int ic_mr_button_connected_25_dark = 2131165376;
			
			// aapt resource value: 0x7F0700C1
			public const int ic_mr_button_connected_25_light = 2131165377;
			
			// aapt resource value: 0x7F0700C2
			public const int ic_mr_button_connected_26_dark = 2131165378;
			
			// aapt resource value: 0x7F0700C3
			public const int ic_mr_button_connected_26_light = 2131165379;
			
			// aapt resource value: 0x7F0700C4
			public const int ic_mr_button_connected_27_dark = 2131165380;
			
			// aapt resource value: 0x7F0700C5
			public const int ic_mr_button_connected_27_light = 2131165381;
			
			// aapt resource value: 0x7F0700C6
			public const int ic_mr_button_connected_28_dark = 2131165382;
			
			// aapt resource value: 0x7F0700C7
			public const int ic_mr_button_connected_28_light = 2131165383;
			
			// aapt resource value: 0x7F0700C8
			public const int ic_mr_button_connected_29_dark = 2131165384;
			
			// aapt resource value: 0x7F0700C9
			public const int ic_mr_button_connected_29_light = 2131165385;
			
			// aapt resource value: 0x7F0700CA
			public const int ic_mr_button_connected_30_dark = 2131165386;
			
			// aapt resource value: 0x7F0700CB
			public const int ic_mr_button_connected_30_light = 2131165387;
			
			// aapt resource value: 0x7F0700CC
			public const int ic_mr_button_connecting_00_dark = 2131165388;
			
			// aapt resource value: 0x7F0700CD
			public const int ic_mr_button_connecting_00_light = 2131165389;
			
			// aapt resource value: 0x7F0700CE
			public const int ic_mr_button_connecting_01_dark = 2131165390;
			
			// aapt resource value: 0x7F0700CF
			public const int ic_mr_button_connecting_01_light = 2131165391;
			
			// aapt resource value: 0x7F0700D0
			public const int ic_mr_button_connecting_02_dark = 2131165392;
			
			// aapt resource value: 0x7F0700D1
			public const int ic_mr_button_connecting_02_light = 2131165393;
			
			// aapt resource value: 0x7F0700D2
			public const int ic_mr_button_connecting_03_dark = 2131165394;
			
			// aapt resource value: 0x7F0700D3
			public const int ic_mr_button_connecting_03_light = 2131165395;
			
			// aapt resource value: 0x7F0700D4
			public const int ic_mr_button_connecting_04_dark = 2131165396;
			
			// aapt resource value: 0x7F0700D5
			public const int ic_mr_button_connecting_04_light = 2131165397;
			
			// aapt resource value: 0x7F0700D6
			public const int ic_mr_button_connecting_05_dark = 2131165398;
			
			// aapt resource value: 0x7F0700D7
			public const int ic_mr_button_connecting_05_light = 2131165399;
			
			// aapt resource value: 0x7F0700D8
			public const int ic_mr_button_connecting_06_dark = 2131165400;
			
			// aapt resource value: 0x7F0700D9
			public const int ic_mr_button_connecting_06_light = 2131165401;
			
			// aapt resource value: 0x7F0700DA
			public const int ic_mr_button_connecting_07_dark = 2131165402;
			
			// aapt resource value: 0x7F0700DB
			public const int ic_mr_button_connecting_07_light = 2131165403;
			
			// aapt resource value: 0x7F0700DC
			public const int ic_mr_button_connecting_08_dark = 2131165404;
			
			// aapt resource value: 0x7F0700DD
			public const int ic_mr_button_connecting_08_light = 2131165405;
			
			// aapt resource value: 0x7F0700DE
			public const int ic_mr_button_connecting_09_dark = 2131165406;
			
			// aapt resource value: 0x7F0700DF
			public const int ic_mr_button_connecting_09_light = 2131165407;
			
			// aapt resource value: 0x7F0700E0
			public const int ic_mr_button_connecting_10_dark = 2131165408;
			
			// aapt resource value: 0x7F0700E1
			public const int ic_mr_button_connecting_10_light = 2131165409;
			
			// aapt resource value: 0x7F0700E2
			public const int ic_mr_button_connecting_11_dark = 2131165410;
			
			// aapt resource value: 0x7F0700E3
			public const int ic_mr_button_connecting_11_light = 2131165411;
			
			// aapt resource value: 0x7F0700E4
			public const int ic_mr_button_connecting_12_dark = 2131165412;
			
			// aapt resource value: 0x7F0700E5
			public const int ic_mr_button_connecting_12_light = 2131165413;
			
			// aapt resource value: 0x7F0700E6
			public const int ic_mr_button_connecting_13_dark = 2131165414;
			
			// aapt resource value: 0x7F0700E7
			public const int ic_mr_button_connecting_13_light = 2131165415;
			
			// aapt resource value: 0x7F0700E8
			public const int ic_mr_button_connecting_14_dark = 2131165416;
			
			// aapt resource value: 0x7F0700E9
			public const int ic_mr_button_connecting_14_light = 2131165417;
			
			// aapt resource value: 0x7F0700EA
			public const int ic_mr_button_connecting_15_dark = 2131165418;
			
			// aapt resource value: 0x7F0700EB
			public const int ic_mr_button_connecting_15_light = 2131165419;
			
			// aapt resource value: 0x7F0700EC
			public const int ic_mr_button_connecting_16_dark = 2131165420;
			
			// aapt resource value: 0x7F0700ED
			public const int ic_mr_button_connecting_16_light = 2131165421;
			
			// aapt resource value: 0x7F0700EE
			public const int ic_mr_button_connecting_17_dark = 2131165422;
			
			// aapt resource value: 0x7F0700EF
			public const int ic_mr_button_connecting_17_light = 2131165423;
			
			// aapt resource value: 0x7F0700F0
			public const int ic_mr_button_connecting_18_dark = 2131165424;
			
			// aapt resource value: 0x7F0700F1
			public const int ic_mr_button_connecting_18_light = 2131165425;
			
			// aapt resource value: 0x7F0700F2
			public const int ic_mr_button_connecting_19_dark = 2131165426;
			
			// aapt resource value: 0x7F0700F3
			public const int ic_mr_button_connecting_19_light = 2131165427;
			
			// aapt resource value: 0x7F0700F4
			public const int ic_mr_button_connecting_20_dark = 2131165428;
			
			// aapt resource value: 0x7F0700F5
			public const int ic_mr_button_connecting_20_light = 2131165429;
			
			// aapt resource value: 0x7F0700F6
			public const int ic_mr_button_connecting_21_dark = 2131165430;
			
			// aapt resource value: 0x7F0700F7
			public const int ic_mr_button_connecting_21_light = 2131165431;
			
			// aapt resource value: 0x7F0700F8
			public const int ic_mr_button_connecting_22_dark = 2131165432;
			
			// aapt resource value: 0x7F0700F9
			public const int ic_mr_button_connecting_22_light = 2131165433;
			
			// aapt resource value: 0x7F0700FA
			public const int ic_mr_button_connecting_23_dark = 2131165434;
			
			// aapt resource value: 0x7F0700FB
			public const int ic_mr_button_connecting_23_light = 2131165435;
			
			// aapt resource value: 0x7F0700FC
			public const int ic_mr_button_connecting_24_dark = 2131165436;
			
			// aapt resource value: 0x7F0700FD
			public const int ic_mr_button_connecting_24_light = 2131165437;
			
			// aapt resource value: 0x7F0700FE
			public const int ic_mr_button_connecting_25_dark = 2131165438;
			
			// aapt resource value: 0x7F0700FF
			public const int ic_mr_button_connecting_25_light = 2131165439;
			
			// aapt resource value: 0x7F070100
			public const int ic_mr_button_connecting_26_dark = 2131165440;
			
			// aapt resource value: 0x7F070101
			public const int ic_mr_button_connecting_26_light = 2131165441;
			
			// aapt resource value: 0x7F070102
			public const int ic_mr_button_connecting_27_dark = 2131165442;
			
			// aapt resource value: 0x7F070103
			public const int ic_mr_button_connecting_27_light = 2131165443;
			
			// aapt resource value: 0x7F070104
			public const int ic_mr_button_connecting_28_dark = 2131165444;
			
			// aapt resource value: 0x7F070105
			public const int ic_mr_button_connecting_28_light = 2131165445;
			
			// aapt resource value: 0x7F070106
			public const int ic_mr_button_connecting_29_dark = 2131165446;
			
			// aapt resource value: 0x7F070107
			public const int ic_mr_button_connecting_29_light = 2131165447;
			
			// aapt resource value: 0x7F070108
			public const int ic_mr_button_connecting_30_dark = 2131165448;
			
			// aapt resource value: 0x7F070109
			public const int ic_mr_button_connecting_30_light = 2131165449;
			
			// aapt resource value: 0x7F07010A
			public const int ic_mr_button_disabled_dark = 2131165450;
			
			// aapt resource value: 0x7F07010B
			public const int ic_mr_button_disabled_light = 2131165451;
			
			// aapt resource value: 0x7F07010C
			public const int ic_mr_button_disconnected_dark = 2131165452;
			
			// aapt resource value: 0x7F07010D
			public const int ic_mr_button_disconnected_light = 2131165453;
			
			// aapt resource value: 0x7F07010E
			public const int ic_mr_button_grey = 2131165454;
			
			// aapt resource value: 0x7F07010F
			public const int ic_mtrl_chip_checked_black = 2131165455;
			
			// aapt resource value: 0x7F070110
			public const int ic_mtrl_chip_checked_circle = 2131165456;
			
			// aapt resource value: 0x7F070111
			public const int ic_mtrl_chip_close_circle = 2131165457;
			
			// aapt resource value: 0x7F070112
			public const int ic_vol_type_speaker_dark = 2131165458;
			
			// aapt resource value: 0x7F070113
			public const int ic_vol_type_speaker_group_dark = 2131165459;
			
			// aapt resource value: 0x7F070114
			public const int ic_vol_type_speaker_group_light = 2131165460;
			
			// aapt resource value: 0x7F070115
			public const int ic_vol_type_speaker_light = 2131165461;
			
			// aapt resource value: 0x7F070116
			public const int ic_vol_type_tv_dark = 2131165462;
			
			// aapt resource value: 0x7F070117
			public const int ic_vol_type_tv_light = 2131165463;
			
			// aapt resource value: 0x7F070119
			public const int mr_button_connected_dark = 2131165465;
			
			// aapt resource value: 0x7F07011A
			public const int mr_button_connected_light = 2131165466;
			
			// aapt resource value: 0x7F07011B
			public const int mr_button_connecting_dark = 2131165467;
			
			// aapt resource value: 0x7F07011C
			public const int mr_button_connecting_light = 2131165468;
			
			// aapt resource value: 0x7F07011D
			public const int mr_button_dark = 2131165469;
			
			// aapt resource value: 0x7F07011E
			public const int mr_button_light = 2131165470;
			
			// aapt resource value: 0x7F07011F
			public const int mr_dialog_close_dark = 2131165471;
			
			// aapt resource value: 0x7F070120
			public const int mr_dialog_close_light = 2131165472;
			
			// aapt resource value: 0x7F070121
			public const int mr_dialog_material_background_dark = 2131165473;
			
			// aapt resource value: 0x7F070122
			public const int mr_dialog_material_background_light = 2131165474;
			
			// aapt resource value: 0x7F070123
			public const int mr_group_collapse = 2131165475;
			
			// aapt resource value: 0x7F070124
			public const int mr_group_expand = 2131165476;
			
			// aapt resource value: 0x7F070125
			public const int mr_media_pause_dark = 2131165477;
			
			// aapt resource value: 0x7F070126
			public const int mr_media_pause_light = 2131165478;
			
			// aapt resource value: 0x7F070127
			public const int mr_media_play_dark = 2131165479;
			
			// aapt resource value: 0x7F070128
			public const int mr_media_play_light = 2131165480;
			
			// aapt resource value: 0x7F070129
			public const int mr_media_stop_dark = 2131165481;
			
			// aapt resource value: 0x7F07012A
			public const int mr_media_stop_light = 2131165482;
			
			// aapt resource value: 0x7F07012B
			public const int mr_vol_type_audiotrack_dark = 2131165483;
			
			// aapt resource value: 0x7F07012C
			public const int mr_vol_type_audiotrack_light = 2131165484;
			
			// aapt resource value: 0x7F07012D
			public const int mtrl_snackbar_background = 2131165485;
			
			// aapt resource value: 0x7F07012E
			public const int mtrl_tabs_default_indicator = 2131165486;
			
			// aapt resource value: 0x7F07012F
			public const int navigation_empty_icon = 2131165487;
			
			// aapt resource value: 0x7F070130
			public const int notification_action_background = 2131165488;
			
			// aapt resource value: 0x7F070131
			public const int notification_bg = 2131165489;
			
			// aapt resource value: 0x7F070132
			public const int notification_bg_low = 2131165490;
			
			// aapt resource value: 0x7F070133
			public const int notification_bg_low_normal = 2131165491;
			
			// aapt resource value: 0x7F070134
			public const int notification_bg_low_pressed = 2131165492;
			
			// aapt resource value: 0x7F070135
			public const int notification_bg_normal = 2131165493;
			
			// aapt resource value: 0x7F070136
			public const int notification_bg_normal_pressed = 2131165494;
			
			// aapt resource value: 0x7F070137
			public const int notification_icon_background = 2131165495;
			
			// aapt resource value: 0x7F070138
			public const int notification_template_icon_bg = 2131165496;
			
			// aapt resource value: 0x7F070139
			public const int notification_template_icon_low_bg = 2131165497;
			
			// aapt resource value: 0x7F07013A
			public const int notification_tile_bg = 2131165498;
			
			// aapt resource value: 0x7F07013B
			public const int notify_panel_notification_icon_bg = 2131165499;
			
			// aapt resource value: 0x7F07013C
			public const int tooltip_frame_dark = 2131165500;
			
			// aapt resource value: 0x7F07013D
			public const int tooltip_frame_light = 2131165501;
			
			// aapt resource value: 0x7F07013E
			public const int waterfront = 2131165502;
			
			// aapt resource value: 0x7F07013F
			public const int xamarin_logo = 2131165503;
			
			// aapt resource value: 0x7F070140
			public const int xaml = 2131165504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme_Base = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
